# Generated by Django 4.2.1 on 2023-06-05 10:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='age',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default=django.utils.timezone.now, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='region',
            field=models.CharField(choices=[('Awdal', 'Awdal'), ('Bakool', 'Bakool'), ('Banaadir', 'Banaadir'), ('Bari', 'Bari'), ('Bay', 'Bay'), ('Galguduud', 'Galguduud'), ('Gedo', 'Gedo'), ('Hiraan', 'Hiraan'), ('Jubbada Dhexe', 'Jubbada Dhexe'), ('Jubbada Hoose', 'Jubbada Hoose'), ('Mudug', 'Mudug'), ('Nugaal', 'Nugaal'), ('Sanaag', 'Sanaag'), ('Shabeellaha Dhexe', 'Shabeellaha Dhexe'), ('Shabeellaha Hoose', 'Shabeellaha Hoose'), ('Sool', 'Sool'), ('Togdheer', 'Togdheer'), ('Woqooyi Galbeed', 'Woqooyi Galbeed')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
